[package]
name = "kile"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wayland-scanner = "0.30.0"
wayland-client = "0.30.1"
kilexpr = { git="https://gitlab.com/snakedye/kilexpr" }
